language: python
sudo: false
python:
  - 2.7
  - 3.6
install:
  - pip install -r requirements.txt
script:
  - ansible-playbook tests/test.yml
  - ansible-playbook tests/test.yml -e "license_changer_check_mode=true"
  - ansible-playbook license_project.yml -e "license_changer_check_mode=true"
