---
language: python
sudo: false
python:
  - 2.7
  - 3.6
install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
matrix:
  include:
    - script:
        - ansible-playbook tests/test.yml
        - ansible-playbook tests/test.yml -e "license_changer_check_mode=true"
    - script:
        - ansible-playbook license_project.yml -e "license_changer_check_mode=true"
        - yamllint -s .
        - ansible-lint .
