---
language: python
sudo: false
python:
  - 2.7
  - 3.6


matrix:
  include:
    - install:
        - pip install -r requirements.txt
      script:
        - ansible-playbook tests/test.yml
        - ansible-playbook tests/test.yml -e "license_changer_check_mode=true"

    - install:
        - pip install -r requirements.txt
        - pip install -r dev-requirements.txt
      script:
        - ansible-playbook license_project.yml -e "license_changer_check_mode=true"
        - yamllint -s $(git ls-files | grep -E '*.ya?ml$')
        - ansible-lint .
