- hosts: localhost
  become: no
  vars:
    test_files:
      - regexp: ".sh$"
        prefix: "# "
        suffix: ""
        start: "#!/bin/bash"
        end: "^$"
        marker: "#\t\t"
      - regexp: ".py$"
        prefix: "# "
        suffix: ""
        start: "BOF"
        end: "^$"
        marker: "#\t\t"
      - regexp: ".scala$"
        prefix: "  * "
        suffix: ""
        start: "/**"
        end: "*/"
        marker: "// "
      - regexp: ".yaml.test$"
        prefix: "#"
        suffix: ""
        start: "---$"
        end: "^$"
        marker: "#__"
  tasks:
    - name: Run license changer on test files
      include_role:
        name: license-changer
      vars:
        license_changer_project_dir: "{{playbook_dir}}/tests/files"
        license_changer_project_file_regexp: "{{test_item.regexp}}"
        license_changer_header_prefix: "{{test_item.prefix}}"
        license_changer_header_suffix: "{{test_item.suffix}}"
        license_changer_header_start: "{{test_item.start}}"
        license_changer_header_end: "{{test_item.end}}"
        license_changer_header_marker: "{{test_item.marker}}"
      with_items: "{{test_files}}"
      loop_control:
        loop_var: test_item
